---
title: "Quarto Combined Example"
author: "Aaron M. Geller"
date: "6/14/2023"
theme: journal
format:
    html:
        code-fold: true
        code-tools: true
---

## Interactive contour plot with linear regretion fit lines created with [`ggplot2`](https://ggplot2.tidyverse.org/) and [`plotly`](https://plotly.com/ggplot2/) using R (@fig-iris-Rplotly).

```{r}
#| label: load-data

library(datasets)

data(iris)
head(iris)
```


```{r}
#| label: fig-iris-Rplotly
#| fig-cap: "Interactive contour plot showing iris flower data."
#| warning: false

library(plotly)

g <- ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color = Species)) + 
    geom_density2d() + 
    geom_smooth(method = "lm", formula = y~x) +
    theme_bw() + 
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
ggplotly(g)
```


## Static corner plot created with  [`seaborn`](https://seaborn.pydata.org/) in Python (@fig-iris-python).


```{python}
#| label: fig-iris-python
#| fig-cap: "Corner plot created showing iris flower data."

import seaborn as sns

p = sns.PairGrid(r.iris, diag_sharey = False, hue = 'Species', corner = True)
p.map_lower(sns.scatterplot).map_diag(sns.kdeplot).add_legend(bbox_to_anchor = (0.6, 0.6))
```

