---
title: "Quarto R Example"
author: "Aaron M. Geller"
date: "6/14/2023"
format:
    html:
        code-fold: true
        code-tools: true
---

# Load in the data

Use the standard "iris" flower dataset from the [`datasets`](https://rdocumentation.org/packages/datasets/versions/3.6.2) library.

```{r}
#| label: load-data

library(datasets)

data(iris)
head(iris)
```

# Generate a corner plot (@fig-iris-corner)

Use [`ggpairs`](https://ggobi.github.io/ggally/reference/ggpairs.html) from the  `GGally` library.

```{r}
#| label: fig-iris-corner
#| fig-cap: "Iris corner plot."
#| warning: false

library(GGally)

ggpairs(iris, columns = 1:4, legend = 1, switch = 'both',
    mapping = aes(colour = Species),
    diag = list(continuous = wrap("densityDiag", alpha = 0), mapping = aes(fill = Species)),
    lower = list(continuous = "points"),
    upper = list(continuous = "blank")
) + 
theme_bw() + 
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
```


# Generate an interactive scatter plot with [`plotly`](https://plotly.com/ggplot2/) (@fig-iris-plotly)

```{r}
#| label: fig-iris-plotly
#| fig-cap: "Iris interactive scatter plot."
#| warning: false

library(plotly)

g <- ggplot(iris, aes(x = Sepal.Length, y = Petal.Width, color = Species)) + 
    geom_point() + 
    theme_bw() + 
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
    
ggplotly(g)
```
